version: '3.2'
services:
  migration:
    build: .
    command: bash -c "python listener.py"
    volumes:
      - ./conf:/usr/src/app/conf # 配置文件位置,里面是config.yaml
      - ./output:/usr/src/app/output # 登录记录插入日志位置
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"      